### ISSUE TITLE
Unknown column 'pr.project_id' in 'field list'

### ISSUE THREAD

**Issue by maramk** [caseysoftware/web2project-notebook#1]
Dear Casey,

I do get the following error using notebook in the stable web2project

**Unknown column 'pr.project_id' in 'field list'**

Thank you.

Kind regards,

Mara Kriel
mara_kriel@yahoo.com

**Comment by caseysoftware** [comment]
Sorry for the delay on this one. I just did some major cleanups of the module and it should work for you now.

Here are the open issues:
http://bugs.web2project.net/view.php?id=1721
http://bugs.web2project.net/view.php?id=1722

**Comment by caseysoftware** [comment]
*bump*

This is to make sure you have the new url for this module.
