### ISSUE TITLE
created by broken in note view

### ISSUE THREAD

**Issue by opto** [caseysoftware/web2project-notebook#12]
date shown is 

  | , 00/Nov/0000 12:00 am
-- | --

no user name shown

**Comment by opto** [comment]
pre create hook is missing
why isn't this done in baseclass precreate? all objects shoud have created and modified date

**Comment by caseysoftware** [comment]
I completely agree and I think that should be in the next major release since many tables will need to be updated.

**Comment by opto** [comment]
I did this alredy for pre create, pre update, pre store but didn't upload yet
Will close the issue once uploaded to git

**Comment by caseysoftware** [comment]
Oops, that was the wrong commit, it was actually this one:

https://github.com/web2project/modules-notebook/commit/cb97e061246ab74cdc57e4e7edca969b9c9577ff

Please merge & rebase with master. :)
